<?php session_start(); require_once __DIR__.'/_helpers.php';
$schoolId=$_GET['school_id']??''; $sid=$_GET['student_id']??''; $school=null; foreach((schools_config()['schools']??[]) as $s){ if(($s['school_id']??'')===$schoolId){$school=$s;break;} }
$rows=read_school_results($schoolId); $row=null; foreach($rows as $r){ if(($r['student_id']??'')===$sid){$row=$r;break;} }
$dirs=['IT','Muhandislik','Tibbiyot','Iqtisodiyot','Pedagogika']; $available=$school['directions']??$dirs;
?><!doctype html><html lang="uz"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="assets/style.css"><title>O‘quvchi</title></head><body><div class="container"><section class="card"><a href="school_students.php?school_id=<?=urlencode($schoolId)?>">← Orqaga</a><?php if($row): ?>
<h1><?=h($row['FIO']??'')?></h1><div class="profile-head"><div><p><b>ID:</b> <?=h($row['student_id']??'')?></p><p><b>Sinf:</b> <?=h($row['Sinf']??'')?></p><p><b>Maktab:</b> <?=h($school['school_name']??'')?></p><p><b>Temporal coverage:</b> <?=h($row['temporal_years_count']??'')?>/11 — <?=h($row['temporal_coverage_level']??'')?></p></div><div class="rec-box"><span>Global tavsiya</span><strong><?=h($row['recommended_direction']??'')?></strong><em><?=pct($row['recommendation_confidence']??'')?> ishonchlilik</em></div></div>
<section class="grid2"><div class="card"><h2>5 ta global yo‘nalish</h2><?php foreach($dirs as $d): $val=(float)($row['prob_'.$d]??0)*100; ?><div class="prob-row"><span><?=h($d)?></span><b><?=number_format($val,2)?>%</b><div class="bar"><i style="width:<?=min(100,$val)?>%"></i></div></div><?php endforeach; ?></div><div class="card"><h2>Maktab ichidagi tavsiya</h2><?php $bestSchool='';$bestVal=-1; foreach($available as $d){$v=(float)($row['prob_'.$d]??0); if($v>$bestVal){$bestVal=$v;$bestSchool=$d;}} ?><p class="bigrec"><?=h($bestSchool)?></p><p>Ishonchlilik: <b><?=pct($bestVal)?></b></p><?php if(($row['recommended_direction']??'')!==$bestSchool): ?><p class="alert">Global tavsiya <?=h($row['recommended_direction']??'')?>, lekin bu maktabdagi mavjud yo‘nalishlar ichida eng mosi <?=h($bestSchool)?>.</p><?php endif; ?></div></section>
<section class="card"><h2>Rivojlanish trayektoriyasi</h2><?php $hist=[]; if(!empty($row['temporal_history'])){$hist=json_decode($row['temporal_history'],true); if(!is_array($hist))$hist=[];} ?><?php if($hist): ?><div class="timeline"><?php foreach($hist as $it): ?><div class="tl-item"><span><?=h(($it['grade']??'').'-sinf')?></span><b><?=h($it['direction']??'')?></b><em><?=h($it['year_mean']??'')?></em></div><?php endforeach; ?></div><?php else: ?><p class="muted">Temporal tarix mavjud emas.</p><?php endif; ?></section>
<section class="card"><h2>Tavsiya sababi</h2><p><?=h($row['recommendation_reason']??'')?></p><p><?=h($row['selected_direction_advice']??'')?></p></section>
<?php else: ?><h1>O‘quvchi topilmadi</h1><?php endif; ?></section></div></body></html>