<?php session_start(); require_once __DIR__.'/_helpers.php';
$schoolId=$_GET['school_id'] ?? ''; $school=null; foreach((schools_config()['schools']??[]) as $s){ if(($s['school_id']??'')===$schoolId){$school=$s;break;} }
if(!$school){ $school=current_school(); $schoolId=$school['school_id']??''; }
if(!$school){ header('Location: school_login.php'); exit; }
$rows=read_school_results($schoolId); $q=trim($_GET['q']??''); $class=trim($_GET['class']??''); $dirs=['IT','Muhandislik','Tibbiyot','Iqtisodiyot','Pedagogika'];
$classes=[]; foreach($rows as $r){ if(!empty($r['Sinf']))$classes[$r['Sinf']]=1; } ksort($classes);
$filtered=[]; foreach($rows as $r){ if($class!=='' && ($r['Sinf']??'')!==$class) continue; if($q!=='' && stripos(($r['FIO']??'').' '.($r['student_id']??''),$q)===false) continue; $filtered[]=$r; }
?><!doctype html><html lang="uz"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="assets/style.css"><title>Maktab o‘quvchilari</title></head><body><div class="container">
<header class="topbar"><h1><?=h($school['school_name'])?> — o‘quvchilar</h1><nav class="nav"><a href="school_dashboard.php?school_id=<?=urlencode($schoolId)?>">Maktab dashboard</a><a href="prediction_mode.php">Dataset yuklash</a></nav></header>
<section class="card"><form method="get" class="filters"><input type="hidden" name="school_id" value="<?=h($schoolId)?>"><input type="text" name="q" value="<?=h($q)?>" placeholder="F.I.O yoki ID"><select name="class"><option value="">Barcha sinflar</option><?php foreach(array_keys($classes) as $c): ?><option value="<?=h($c)?>" <?=$class===$c?'selected':''?>><?=h($c)?></option><?php endforeach; ?></select><button>Saralash</button><a class="btn secondary" href="school_students.php?school_id=<?=urlencode($schoolId)?>">Tozalash</a></form><p class="muted">Topildi: <?=count($filtered)?> ta.</p></section>
<section class="card"><div class="table-wrap"><table><thead><tr><th>ID</th><th>F.I.O</th><th>Sinf</th><th>Temporal coverage</th><th>Global tavsiya</th><th>Ishonch</th><?php foreach($dirs as $d): ?><th><?=h($d)?></th><?php endforeach; ?><th>Amal</th></tr></thead><tbody>
<?php foreach($filtered as $r): ?><tr><td><?=h($r['student_id']??'')?></td><td><?=h($r['FIO']??'')?></td><td><?=h($r['Sinf']??'')?></td><td><?=h($r['temporal_years_count']??'')?>/11 — <?=h($r['temporal_coverage_level']??'')?></td><td><b><?=h($r['recommended_direction']??'')?></b></td><td><?=pct($r['recommendation_confidence']??'')?></td><?php foreach($dirs as $d): ?><td><?=pct($r['prob_'.$d]??'')?></td><?php endforeach; ?><td><a class="mini" href="school_student.php?school_id=<?=urlencode($schoolId)?>&student_id=<?=urlencode($r['student_id']??'')?>">Ko‘rish</a></td></tr><?php endforeach; ?>
</tbody></table></div></section></div></body></html>